server:
  port: 18000
  servlet:
    context-path: /
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/bill?useSSL=false&serverTimezone=UTC
    username: root
    password: root
  application:
    name: bill
mybatis-plus:
  global-config:
    # 全局配置
    db-config:
      # 数据库配置
      id-type: assign_id
# springdoc-openapi项目配置
knife4j:
  enable: true
  setting:
    language: zh_cn

